name: antfast
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # Functional Programming
  dartz: ^0.10.1

  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3

  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  # flutter_local_notifications: ^17.2.2

  # Navigation
  go_router: ^14.6.2

  # Utilities
  intl: ^0.20.1
  logger: ^2.5.0
  pinput: ^5.0.0
  country_code_picker: ^3.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  razorpay_flutter: ^1.3.7
  image_picker: ^1.1.2
  crypto: ^3.0.3
  
  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.6


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
